import Head from 'next/head'
import { styled } from 'goober'
import { useState } from 'react'
import { SelectMap } from '@/3_organisms/SelectMap'
import { SelectFlore } from '@/3_organisms/SelectFlore'
import { IconList } from '@/2_molecules/IconList'
import { Map } from '@/1_atoms/Map'

// [ ] リファクタリングされたマップコンポーネント
// [x] Map の階層切り替えスイッチ

const Main = styled('main')`
display: grid;
grid-template-columns: auto 20%;
grid-template-rows: auto 20%;
`

const data: string[] = ['1f', '2f']

export default function Home() {
  const [map, setMapImage] = useState('/R6TAC_ALLMAPS/maps/bank/bank1f.jpg')
  const [flores, setFlores] = useState<string[]>(data)
  return <>
    <Head>
      <title>R6S Board</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Main>
      <Map pass={map} />
      <SelectMap handleChange={(v) => { setMapImage(v) }} />
      <IconList />
      <SelectFlore data={flores} />
    </Main>
  </>
}
