import Head from 'next/head'
import { styled } from 'goober'
import { IconList, IconPalette } from '@/2_molecules/IconList'
import { operators } from '@/_data/operators'
import { DisplayMap } from '@/2_molecules/DisplayMap'
import { useDisplayMap } from '@/hooks/useMap'
import { useMemo } from 'react'

const Main = styled('main')`

.tooltip {/*ツールチップの対象要素*/
	position: relative;
	display: inline-block;
}

.tooltip .tooltiptext {/*ツールチップ本体*/
	visibility: hidden;
	width: 150px;
	background-color: blue;
	text-align: center;
	padding: 5px 0;
	position: absolute;
	top: -4rem;
	left: -3.5rem;
}

.tooltip:hover .tooltiptext {
	visibility: visible;
}

`

export default function Home() {
	const { activeMapFloor } = useDisplayMap()

	const attackers = useMemo(() => operators.filter(it => it.role === 'attack'), [])

	return <>
		<Head>
			<title>R6S Board</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<Main>
			<DisplayMap activeMapFloor={activeMapFloor} />
			<div className="tooltip">MENU1
				<span className="tooltiptext"><IconPalette activeOperators={attackers} /></span>
			</div>
			<IconList />
		</Main>
	</>
}
