import Head from 'next/head'
import { styled } from 'goober'
import { useState } from 'react'
import { Map } from '@/1_atoms/Map'
import map from '../_data/map2.json'

const Main = styled('main')`
display: grid;
grid-template-columns: auto 20%;
grid-template-rows: auto 20%;
`

type Props = {
	data: Flores[]
	handleChange: (_v: string) => void
}

type Props2 = {
	data: Flores[]
	handleChange2: (_w: Flores[]) => void
}

const Maps2: Map2[] = map

const data2: Flores[] = [
	{ flore: 'b1', imgpass: '/R6TAC_ALLMAPS/maps/bank/bankb1.jpg' },
	{ flore: '1f', imgpass: '/R6TAC_ALLMAPS/maps/bank/bank1f.jpg' },
	{ flore: '2f', imgpass: '/R6TAC_ALLMAPS/maps/bank/bank2f.jpg' }
]

const SelectMap = ({ data, handleChange2 }: Props2) => {
	return <select onChange={(e) => handleChange2(Maps2.find(it => it.value === e.target.value)?.flores || data)}>
		{Maps2.map((it, idx) =>
			<option key={idx} value={it.value} id={it.id}>
				{it.label}
			</option>
		)}
	</select>
}

const SelectFlore = ({ data, handleChange }: Props) => {
	return <select onChange={(e) => handleChange(e.target.value)}>
		{data.map((it, idx) =>
			<option key={idx} value={it.imgpass}>
				{it.flore}
			</option>)}
	</select>
}

export default function Home() {
	const [map, setMapImage] = useState('/R6TAC_ALLMAPS/maps/bank/bankb1.jpg')
	const [flores, setFlores] = useState<Flores[]>(data2)
	return <>
		<Head>
			<title>R6S Board</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<Main>
			<Map pass={map} />
			<SelectMap data={flores} handleChange2={setFlores} />
			<SelectFlore data={flores} handleChange={setMapImage} />
		</Main>
	</>
}
